### PR TITLE
Bump futures

### PR DESCRIPTION
**Pull request by OniOni**
### Problem
We have a dependency that pulls in a conflicting version of futures.

### Solution
Loosen constraint on `futures` as to yield a resolvable set of dependencies.

### Result
* This should have no effect on end users. `futures` releases seem to be just bug fixes .
* I ran, `./pants test tests/python/twitter/common/concurrent::`, successfully. 

### Notes
* Let me know if I should run any additional tests
* I'm also happy to go with a pinned version of `futures`, let me know what makes the most sense.

### CODE REVIEW

**Comment by mateor** [comment]
@OniOni works with me at Foursquare. @stuhood or @kwlzn can you rerun the CI for us?

**Comment by OniOni** [comment]
Thanks to whomever reran the build. Looks like failure is same a last time. Will dig into this, thanks!

**Comment by OniOni** [comment]
Wouldn't mind a rerun. I got a green on travis build for my fork: https://travis-ci.org/OniOni/commons/builds/476936976

**Comment by kwlzn** [comment]
reran

**Comment by OniOni** [comment]
@kwlzn thank you so much. Looks like a different failure. Could I bother you for another rerun? 

I'll keep track of failures, hopefully I can try and fix those flakes (if they're flakes, that is)
- test_sampler_base

**Comment by mateor** [comment]
If the CI runs are the most straightforward way to debug, you can turn on travisci.org builds for your forked copy.

This is still free and while it won't matriculate status back here, it gives you access to a rebuild button and a single-node iteration loop

**Comment by OniOni** [comment]
@mateor: I did indeed do this. It failed on the first run, but I did get a green on the second run (https://travis-ci.org/OniOni/commons/builds/476936976). This is why I asked for that rerun 8 days ago as I am fairly confident these are flakes.

To be fair, tests are flaking pretty badly and that is an issue in itself. I'm not convinced that my changes accentuated flakes, but it's hard to tell without historical data.

**Comment by grimreaper** [comment]
Thank you for your contribution. Unfortunately, we’re not going to continue maintaining twitter-commons and are archiving all pull requests.

**Pull request closed without merging**
