### PR TITLE
Update the futures library.

### PR DESCRIPTION
**Pull request by mateor**
This just bumps futures to a more modern version,
some core libraries are pinned to a range that is
later than the current t.c. dep.

This is the minimum-viable change that makes t.c.
libs compatible with our problem lib (boto3).

Testing done: Ran the ci.sh script, which passes.

References: #427

### CODE REVIEW

**Comment by mateor** [comment]
Do you all still use RBC? It looks like the `rbt` tools included in the commons repo is broken since: 146de30657b2f6c07fd16b6f250be0af73e0a2f6

**Comment by brutkin** [comment]
You can just grab an appropriate version from https://www.reviewboard.org/downloads/rbtools/

**Comment by mateor** [comment]
I was just discussing it with stu hood. I am familiar with RBCommons so no problem getting the binary. I just wanted to be sure that it was still the way to review changes.

I will send something up in a bit. Thanks!

**Comment by mateor** [comment]
Submitted as: e8de9d16eda3c22c1a866178f73a12355fc5699c

**Comment by kwlzn** [comment]
FYI - I now have https://rbcommons.com/s/twitter/r/3858/ out for the `./rbt` fix.

**Pull request closed without merging**
