### PR TITLE
[hadoop] change hadoop to hdfs cli

### PR DESCRIPTION
**Pull request by drewrothstein**
This changes the `hadoop` command to `hdfs` (v1 > v2).

### CODE REVIEW

**Comment by Yasumoto** [comment]
Instead of changing outright, perhaps allow some autodetection and configuration?

**Comment by drewrothstein** [comment]
Are you thinking based on version parsing, binary existing, or something else?

**Comment by Yasumoto** [comment]
I'd check for the v2 command in PATH then fallback to v1, but allow configuration for v1.

**Comment by drewrothstein** [comment]
Going to close/re-open to trigger another build.
Looks like the build failed due to things I didn't touch.

**Comment by drewrothstein** [comment]
Locally both of the failed tests pass.
Will retry again.

**Comment by Yasumoto** [comment]
Seems solid to me, :shipit: !

**Comment by drewrothstein** [comment]
RBCommons: https://rbcommons.com/s/twitter/r/4048/

**Pull request closed without merging**
